dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - node_modules
install: true
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn clean install
addons:
  ssh_known_hosts:
    - repo.maven.org