dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
env:
  - TRAVIS_NODE_VERSION="8"
cache:
  directories:
    - $HOME/.m2
    - node_modules
install: true
before_install:

  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
before_script:
  - "export NODE_BIN=`nvm which $TRAVIS_NODE_VERSION`"
  - "export NODE_PATH=`dirname $NODE_BIN`"
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn clean install
addons:
  ssh_known_hosts:
    - repo.maven.org